pub const SPOTIFY_CLIENT_ID: &str = "YOUR_SPOTIFY_CLIENT_ID";
pub const SPOTIFY_CLIENT_SECRET: &str = "YOUR_SPOTIFY_CLIENT_SECRET";

pub const YOUTUBE_CLIENT_ID: &str = "YOUR_YOUTUBE_CLIENT_ID";
pub const YOUTUBE_CLIENT_SECRET: &str = "YOUR_YOUTUBE_CLIENT_SECRET";

pub const LASTFM_API_KEY: &str = "YOUR_LASTFM_API_KEY";
pub const LASTFM_SHARED_SECRET: &str = "YOUR_LASTFM_SHARED_SECRET";
